spring:
  application:
    name: TheDrugPlaceManagementSoftware
  data:
    mongodb:
      #uri: mongodb://wacUser:Uganda!2123017@172.105.59.236:27017/thedrugplace
      authentication-database: admin
      database: thedrugplace
      username: wacUser
      password: Uganda!2123017
      host: 172.105.59.236