spring:
  application:
    name: TheDrugPlaceManagementSoftware

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml

  datasource:
    url: ${YOUR_DB_URL}
    username: ${YOUR_DB_USERNAME}
    password: ${YOUR_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl


management:
  endpoints:
    web:
      exposure:
        include: "*"

grafana:
  url: ${YOUR_GRAFANA_URL}

server:
  port: 8008
