spring:
  application:
    name: TheDrugPlaceManagementSoftware
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:postgresql://siitadb.cp0hvp28oiad.us-east-1.rds.amazonaws.com:5432/siitaDb
    username: postgres
    password: NamonoElgon
    driver-class-name: org.postgresql.Driver
  logging:
    level:
      org.springframework: DEBUG
      org.springframework.boot: DEBUG
  springfox:
    documentation:
      swagger-ui:
        path: /custom-path/swagger-ui
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"

#grafana:
#  url: ${YOUR_GRAFANA_URL}

server:
  port: 8008
