name: Deploy to EC2

on:
  push:
    branches:
      - master # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17 # Adjust the Java version as needed

      - name: Build the Spring application
        run: mvn clean install -DskipTests

      - name: Find siita-server.jar location
        run: |
          find $GITHUB_WORKSPACE -type f -name siita-server.jar
        id: find-jar

      - name: Show JAR file location
        run: |
          echo "siita-server.jar is located at: ${{ steps.find-jar.outputs.stdout }}"

      - name: Copy JAR to EC2
        if: success() # Only proceed if the previous step was successful
        uses: appleboy/scp-action@v0.1.4
        with:
          debug: true
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: /home/runner/work/theDrugPlaceApi/theDrugPlaceApi/target/siita-server.jar
          target: /home/ec2-user/apps/siita-server

#      - name: SSH into EC2 and start the application
#        if: success() # Only proceed if the previous step was successful
#        run: |
#          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'nohup java -jar /home/ec2-user/apps/siita-server/github/workspace/target/siita-server.jar > /dev/null 2>&1 &'
#      - name: SSH into EC2 and start the application

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
          env:
            SSH_HOST: ${{ secrets.EC2_HOST }}
            SSH_USER: ${{ secrets.EC2_USERNAME }}
            SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      - name: List home directory
        run: ssh ec2 'ls -la'
