name: Deploy to EC2

on:
  push:
    branches:
      - master # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust the Java version as needed

      - name: Build the Spring application
        run: mvn clean install -DskipTests

      - name: Find siita-server.jar location
        run: |
          find $GITHUB_WORKSPACE -type f -name siita-server.jar
        id: find-jar

      - name: Show JAR file location
        run: |
          echo "siita-server.jar is located at: ${{ steps.find-jar.outputs.stdout }}"

      - name: Copy JAR to EC2
        if: success()
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: /home/runner/work/theDrugPlaceApi/theDrugPlaceApi/target/siita-server.jar
          target: /home/ec2-user/apps/siita-server/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          cat ssh_key 

      - name: SSH into AWS instance and set permissions
        run: |
          ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod -R 777 /home/ec2-user/apps/*"

      - name: Check if the application is running
        run: |
          result=$(ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pgrep -f siita-server.jar" || true)
          if [ -n "$result" ]; then
            echo "Application is running."
            echo "::set-output name=app_running::true"
          else
            echo "Application is not running."
            echo "::set-output name=app_running::false"
          fi
        id: pgrep

      - name: Terminate existing application if running
        if: success() && steps.pgrep.outputs.app_running == 'true'
        run: |
          echo "Terminating existing application."
          ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pkill -f siita-server.jar"
      

      - name: Start the application
        run: |
          ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "nohup java -jar /home/ec2-user/apps/siita-server/github/workspace/target/siita-server.jar > /dev/null 2>&1 &"

      - name: Wait for the application to start
        run: |
          sleep 10 # Adjust the sleep time based on your application's startup time

      - name: Test the application
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_HOST }}:8008/health)
          if [ $response_code -eq 200 ]; then
            echo "Application is running and healthy."
          else
            echo "Application is not running properly. Response code: $response_code"
            exit 1
          fi
